### ISSUE TITLE
activeperl_x64 repo outdated

### ISSUE THREAD

**Issue by JuliusHibbert** [saltstack/salt-winrepo-ng#1136]
the uris changed to:
http://downloads.activestate.com/ActivePerl/releases/
i would really appreciate it if someone could update the sls. Thank you!

**Comment by TheBigBear** [comment]
why not have a go yourself? I will look it over and merge it ....

**Comment by JuliusHibbert** [comment]
i have absolutely no idea what i'm doing :)

**Comment by TheBigBear** [comment]
@JuliusHibbert ;-) - so what version of activeperl are you seeking to install or upgrade to?

**Comment by JuliusHibbert** [comment]
i rtfm and managed to fork this repo, changed the activeperl_x64.sls according to the path on the ActiveState-server with two new random GUIDs, commited and sent a pull request. dunno if this is the right way and the new sls is going to work.
i've got to install perl on an computer-pool full of win7-minions to get some old perl-scripts working. an older perl-version should do, but perhaps better install an new one. 
sorry, i'm new to git and saltstack ...

**Comment by TerraTalpi** [comment]
Hey @TheBigBear, I checked this and I have seen that he actually opened an unlinked pull-request with #1140 but you did the updates in #1157, #1158, #1159 and #1160. So I guess this issue was just never closed after your patches, right?
