### ISSUE TITLE
nsclient.sls: Wrong version string

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt-winrepo-ng#1154]
Hi,

just tried to install the nsclient package in the latest available version, which is *0.5.0.62* according to the SLS. However, after installation I get:
```
----------
          ID: nsclient
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: nsclient=0.5.0.62
     Started: 14:41:06.488000
    Duration: 20734.0 ms
     Changes:
              ----------
              nsclient:
                  ----------
                  new:
                      0.5.0062
                  old:
----------
```
Please fix.

**Comment by TheBigBear** [comment]
@dhs-rec there is a newer one in the repo can you please check if this pkg now upgrades and behaves as expected, please? I don't use it myself, so cannot make that call.

**Comment by dhs-rec** [comment]
Same issue:
```
----------
          ID: nsclient
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: nsclient=0.5.2.29
     Started: 06:50:04.391000
    Duration: 18640.0 ms
     Changes:
              ----------
              nsclient:
                  ----------
                  new:
                      0.5.2029
                  old:
----------
```

**Comment by twangboy** [comment]
Should be fixed with https://github.com/saltstack/salt-winrepo-ng/issues/1154

**Comment by dhs-rec** [comment]
Why has this been closed when #1154 isn't merged, yet?

**Comment by dhs-rec** [comment]
Oops, haven't seen the change you made.

**Comment by TheBigBear** [comment]
@dhs-rec are we 'good'? is it working for you with the new file that uses jinja variables, to keep it nice and clear?

**Comment by dhs-rec** [comment]
Unfortunately not. The change introduced a Jinja syntax error.

**Comment by TheBigBear** [comment]
@dhs-rec oh sorry, it was actually @twangboy that changed it to using jinja variables ( long overdue, much clearer now - and thanks btw )

**Comment by dhs-rec** [comment]
Just spotted another one. Give me a few seconds...

**Comment by dhs-rec** [comment]
Should be fine now.

**Comment by TheBigBear** [comment]
@dhs-rec sorry you might have noticed but your first jinja fix is not correct. it need to be another if ( ```cpuarch``` ) comparison ... just assuming x86 is not correct pretty sure @twangboy had intended to use the ```elif``` actually comparing or checking for ```x86``` .

**Comment by dhs-rec** [comment]
Done.

**Comment by twangboy** [comment]
Sorry...
