### ISSUE TITLE
atom.sls syntactically broken (pkg.refresh_db fails)

### ISSUE THREAD

**Issue by davelindquist-egistix** [saltstack/salt-winrepo-ng#1215]
In [salt-winrepo-ng/atom.sls](https://github.com/saltstack/salt-winrepo-ng/blob/master/atom.sls), the syntax:
```
atom:
  {% for version in ['1.23.3', '1.8.0', '1.7.3] %}
  '{{ version }}':
```
is broken, and trying to do a pkg.refresh_db fails with the error:
```
        salt-winrepo-ng\atom.sls:
            - Failed to compile 'salt-winrepo-ng\atom.sls': Jinja syntax error: expected token ',', got '{'; line 3

              ---
              atom:
                {% for version in ['1.23.3', '1.8.0', '1.7.3] %}
                '{{ version }}':    <======================
```

To fix, we simply need an extra ' mark at the end of the last version number:
```
atom:
  {% for version in ['1.23.3', '1.8.0', '1.7.3'] %}
  '{{ version }}':
```

**Comment by TheBigBear** [comment]
@davelindquist-egistix thanks for reporting this. it is fixed with https://github.com/saltstack/salt-winrepo-ng/pull/1217

**Comment by davelindquist-egistix** [comment]
Wow, fast work -- thanks!
