### ISSUE TITLE
salt 2018.03: installer command line switch changes

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt-winrepo-ng#1345]
Just flagging up that the salt-minion package will require changing based on changes to the installer's handling of config files. [Link](https://docs.saltstack.com/en/develop/topics/releases/2018.3.0.html#windows-installer-changes-to-existing-config-handling)

**Comment by twangboy** [comment]
The Release Notes were wrong, it has changed more since we updated those. I fixed that in the above PR. The installer should continue to function with the existing package definition and default to using the existing config without changes.

**Comment by dafyddj** [comment]
Thanks for the update.
