### ISSUE TITLE
remote ref does not exist

### ISSUE THREAD

**Issue by prog-dale** [saltstack/salt-winrepo-ng#1357]
[root@blah salt]# salt-run winrepo.update_git_repos
[ERROR   ] Failed to checkout master from winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git': remote ref does not exist
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo

Just upgraded to 2018.3 from 2017 and i get the above error now, saw an old comment about changing repo provider in the master config but cannot find that entry.

ideas ?

**Comment by twangboy** [comment]
Network connectivity? I just ran it successfully on mine.

**Comment by TheBigBear** [comment]
You might still be trying to use the old salt-winrepo instead of the newer winrepo-ng one?

**Comment by prog-dale** [comment]
I checked network and it has not changed and it was working just before on the old version stuck on were else to look for information about where the issue is

**Comment by prog-dale** [comment]
salt-run -l debug winrepo.update_git_repos
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/pagerduty.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pagerduty.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: cloud-salt01.cloudstack.dk
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
[DEBUG   ] LazyLoaded winrepo.update_git_repos
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: cloud-salt01.cloudstack.dk
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/pagerduty.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pagerduty.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20180501154734435008/new; data = {u'fun': u'runner.winrepo.update_git_repos', u'fun_args': [], u'jid': u'20180501154734435008', u'user': u'root', u'_stamp': '2018-05-01T13:47:34.941540'}
[DEBUG   ] gitpython winrepo_provider enabled
[DEBUG   ] Current fetch URL for winrepo remote 'https://github.com/saltstack/salt-winrepo.git': https://github.com/saltstack/salt-winrepo.git (desired: https://github.com/saltstack/salt-winrepo.git)
[DEBUG   ] Current refspecs for winrepo remote 'https://github.com/saltstack/salt-winrepo.git': [u'+refs/heads/*:refs/remotes/origin/*', u'+refs/tags/*:refs/tags/*'] (desired: [u'+refs/heads/*:refs/remotes/origin/*', u'+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for winrepo remote 'https://github.com/saltstack/salt-winrepo.git': true (desired: true)
[DEBUG   ] Set update lock for winrepo remote 'https://github.com/saltstack/salt-winrepo.git'
[DEBUG   ] Fetching winrepo remote 'https://github.com/saltstack/salt-winrepo.git'
[DEBUG   ] Popen(['git', 'fetch', '-v', 'origin'], cwd=/srv/salt/win/repo/salt-winrepo, universal_newlines=True, shell=None)
[DEBUG   ] Removed update lock for winrepo remote 'https://github.com/saltstack/salt-winrepo.git'
[DEBUG   ] Popen(['git', 'cat-file', '--batch-check'], cwd=/srv/salt/win/repo/salt-winrepo, universal_newlines=False, shell=None)
[DEBUG   ] Current fetch URL for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git': https://github.com/saltstack/salt-winrepo-ng.git (desired: https://github.com/saltstack/salt-winrepo-ng.git)
[DEBUG   ] Current refspecs for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git': [u'+refs/heads/*:refs/remotes/origin/*', u'+refs/tags/*:refs/tags/*'] (desired: [u'+refs/heads/*:refs/remotes/origin/*', u'+refs/tags/*:refs/tags/*'])
[DEBUG   ] Current http.sslVerify for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git': true (desired: true)
[DEBUG   ] Set update lock for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git'
[DEBUG   ] Fetching winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git'
[DEBUG   ] Popen(['git', 'fetch', '-v', 'origin'], cwd=/srv/salt/win/repo-ng/salt-winrepo-ng, universal_newlines=True, shell=None)
[DEBUG   ] Removed update lock for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git'
[DEBUG   ] Popen(['git', 'cat-file', '--batch-check'], cwd=/srv/salt/win/repo-ng/salt-winrepo-ng, universal_newlines=False, shell=None)
[DEBUG   ] Set checkout lock for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git'
[DEBUG   ] Popen(['git', 'checkout', 'origin/master'], cwd=/srv/salt/win/repo-ng/salt-winrepo-ng, universal_newlines=False, shell=None)
[DEBUG   ] Removed checkout lock for winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git'
[ERROR   ] Failed to checkout master from winrepo remote 'https://github.com/saltstack/salt-winrepo-ng.git': remote ref does not exist
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20180501154734435008: [u'cloud-salt01.cloudstack.dk_master']
[DEBUG   ] Sending event: tag = salt/run/20180501154734435008/ret; data = {u'fun_args': [], u'jid': u'20180501154734435008', u'return': {u'https://github.com/saltstack/salt-winrepo.git': u'/srv/salt/win/repo/salt-winrepo'}, u'success': True, u'_stamp': '2018-05-01T13:47:37.963402', u'user': u'root', u'fun': u'runner.winrepo.update_git_repos'}
[DEBUG   ] LazyLoaded nested.output
https://github.com/saltstack/salt-winrepo.git:
    /srv/salt/win/repo/salt-winrepo
[INFO    ] Runner completed: 20180501154734435008
[DEBUG   ] Runner return: {u'https://github.com/saltstack/salt-winrepo.git': u'/srv/salt/win/repo/salt-winrepo'}

**Comment by twangboy** [comment]
Can you clone that directory from your master on the command line?

```
git clone https://github.com/saltstack/salt-winrepo-ng.git
```

**Comment by prog-dale** [comment]
[root@cloud-salt01 ~]# git clone https://github.com/saltstack/salt-winrepo-ng.git
Cloning into 'salt-winrepo-ng'...
remote: Counting objects: 7191, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 7191 (delta 7), reused 0 (delta 0), pack-reused 7157
Receiving objects: 100% (7191/7191), 1.67 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (3734/3734), done.

**Comment by prog-dale** [comment]
as a side note did a fresh install on centos 7.3 and salt 2018py3 and following the guide to enable to repo all i get is errors so I wonder if there is a step missing in the guide.
Installed salt-master
installed pip
installed gitpython
installed git
git clone https://github.com/saltstack/salt-winrepo-ng.git ... works
salt-run winrepo.update_git_repos

... 
Exception occurred in runner winrepo.update_git_repos: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/runners/winrepo.py", line 210, in update_git_repos
    force_reset=True)
  File "/usr/lib/python3.4/site-packages/salt/states/git.py", line 701, in latest
    saltenv=__env__)
NameError: name '__env__' is not defined

**Comment by prog-dale** [comment]
A fresh install of 2018py2 works flawlessly (python3 does not work) from the same IP so its not networking.

**Comment by prog-dale** [comment]
Ok will do. 

Any ideas what I can do about my 2017 py2 installation that fails to download the repo ?

**Comment by twangboy** [comment]
You could clone the winrepo down yourself. The only one you need, unless you have really old minions (2015.8), is salt-winrepo-ng. It goes into `/srv/salt/win/repo-ng` by default.
