### ISSUE TITLE
Jenkins CI Testing for salt-winrepo-ng

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt-winrepo-ng#1379]
Suggestion
- Pull down the latest production release.
- Setup a Master Linux and Minion Windows
- Run pkg.refresh_db on the Windows Minion
- Check for errors.

**Comment by TheBigBear** [comment]
@damon-atkins does it have to be on jenkins ci? 

I already do have a working CI setup on travis-ci? 

[https://travis-ci.org/TheBigBear/salt-winrepo-ng](url)

And I am maintaining a 'branch' for travis-ci checking on my repo ``` travis-ci_cron_daily```and sync it to upstream origin as well. 
Have stopped fixing issues ( and updating it ) on the very old winrepo repo though, so currently only winrepo-ng is being checked.

Is there a jenkins ci integration with github that works as easy and out of the box with no changes like it did for me using [https://travis-ci.org](url) ?

**Comment by damon-atkins** [comment]
Sounds good.  (links seem to be broken)

I'm still working on replacing this so that version hard coding is no longer required, no full_name **exact** matching, versions of installer available are dynamic and just in time tempting (pipe yaml, jinja, python etc).   Just taking a lot longer than plan and a lot of spare moments.

**Comment by TheBigBear** [comment]
@damon-atkins anything I can do to help, or test and give feedback or help improve it ...? I still think that having or "subverting" the chocolatey installer would be so much easier and so much more efficient ....

**Comment by TheBigBear** [comment]
@damon-atkins thanks for the heads up about the 404 broken links, will have a look, but frankly am getting tired of the very very laborious manual work fo thing to stay on top of this. windows installers are a PAIN !!!

**Comment by damon-atkins** [comment]
That's why plan to move to dynamic version. I..E. Render when the refresh_db but also
 render the required package definition in install and remove. It will be as simple as the current version to use or as complex as choc if python is used in the package definition template.  Next to no maintenance and pillar overrides.

**Comment by damon-atkins** [comment]
Hi @TheBigBear  are you on https://saltstackcommunity.slack.com/ ?

**Comment by damon-atkins** [comment]
See https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/salt-cloud/CcLKDWjdfzk

**Comment by twangboy** [comment]
@TheBigBear That's our community slack channel. We have a windows channel that I monitor.
