### ISSUE TITLE
64bit ProgramFiles: question

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt-winrepo-ng#140]
I'm seeing this convention in the package definitions and it seems backward to me... maybe I am not understanding properly where windows puts 64bit executables.

```
# just 32-bit x86 installer available
{% if grains['cpuarch'] == 'AMD64' %}
    {% set PROGRAM_FILES = "%ProgramFiles(x86)%" %}
{% else %}
    {% set PROGRAM_FILES = "%ProgramFiles%" %}
{% endif %}
```

**Comment by TheBigBear** [comment]
@rterbush ;-) yes I know what you mean. ;-) But unfortunately this is the "right" way up for MS Windows.

I can only guess that 64-bit came along as a bit of a surprise and they asked themselves what shall we call the 32-bit program files folder on our 64-bit system where we of course want the 64-bit programs to live under 'c:\Program Files\' ? 

And came up with c:\Program Files (x86)\' to put 32-bit files when installed under a 64-bit OS. 

And now we have the result that the very same 32-bit program when installed under a 32-bit winodws lives in:

"c:\Program Files\"   and when installed on a 64-bit windows lives under
c:\Program Files (x86)\'  

;-)

**Comment by rterbush** [comment]
Just shoot me...
