### ISSUE TITLE
Git 2.6.3 fails to install correctly

### ISSUE THREAD

**Issue by johnccfm** [saltstack/salt-winrepo-ng#142]
Git 2.6.3 (64 bit) installation fails on my Windows Server 2012R2 system according to Salt (although the software is actually installed).

Git's installer seems to be writing the uninstall key to the registry at:-

    HCKU\Software\Microsoft\Windows\CurrentVersion\Uninstall 

The code in win_pkg.py only iterates:-

    HKLM\Software\Microsoft\Windows\CurrentVersion\Uninstall
    HKLM\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall

Therefore the package manager always thinks it has failed to install even when it has and reports a failure.

Git 2.6.2 seems to be OK.

**Comment by TheBigBear** [comment]
@johnccfm this would appear to be related to packaging issues upstream. ;-) They chnaged parameters for the Inno installer and got it wrong and now got some 'side-effect'.

https://github.com/git-for-windows/git/issues/526
https://github.com/git-for-windows/build-extra/pull/86

I'd suggest to wait for the upstream fix. AFAIK the salt winrepo-ng installer does correctly detect 'user installs'  in other sceanrios, so this might not be failing EXACTLY for the reasons you stated above.

@jfindlay @twangboy can you confirm whether you also think the uninstaller also needs to search the HKCU (current user) hive in the registry?

**Comment by johnccfm** [comment]
@twangboy I actually looked in vain before for a way to run a command as a user in Salt on Windows, to do per-user things. I'd be very surprised if Salt manages per-user installs. Software that installs in the user account only would be useless in Salt, because it would install in the SYSTEM account and not be available to any regular user.

**Comment by twangboy** [comment]
@johnccfm I'm not sure it's possible without knowing the user's password, but I'm not hacker. There are registry issues to consider as well. It would be a mess... unless you knew the password and could actually log in as that user.

I did get runas to work for windows, but again it requires that you know the password for the user. It's also not available until the next release of salt which won't be until early next year.

`pkg.list_pkgs`, and therefore `pkg.install`, is only going to show software that is installed for all users. If they're putting the registry key in HKCU, then salt's not going to find that.

**Comment by TheBigBear** [comment]
2.6.4 is released and works as expected.
