### ISSUE TITLE
salt-minion upgrade reports as failed although was successful

### ISSUE THREAD

**Issue by getSurreal** [saltstack/salt-winrepo-ng#1523]
It appears when you run these states to upgrade the salt-minion that it always reports as a failure.  I'm assuming because it has to stop the salt-minion service when the background task is running the upgrade.  Is there a way to change how this reports?  Example output below of a failed state, but in actuality the salt-minion was upgraded successfully.

Minion version upgrade from 2018.3.2 to 2018.3.3 Py2.

```
wintestserver:
----------
          ID: windows_salt_minion
    Function: pkg.installed
        Name: salt-minion-py2
      Result: False
     Comment: The following packages failed to install/update: salt-minion-py2=2018.3.3
     Started: 14:43:37.108000
    Duration: 2125.0 ms
     Changes:
              ----------
              salt-minion-py2:
                  ----------
                  install status:
                      task started

Summary for wddcsdiaas12.mkappsdev.com
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:   2.125 s

```

State File:
```
windows_salt_minion:
  pkg.installed:
    - name: salt-minion-py2
    - version: latest
    - allow_updates: True

```
Command:
`salt 'wintestserver' state.apply win.salt-minion`

Master:
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: 1.6.1
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by twangboy** [comment]
@getSurreal Yeah, it's difficult. `pkg.install` handles salt a little differently. It uses the task_scheduler to run the installer. The first thing the installer does is kill the salt-minion service.
So the best salt can do is start the task and then return that it did so... because it will soon die. Outside of creating a standalone program that handles the salt service and upgrading salt I don't know what else we could do. I'm open to suggestions.

**Comment by getSurreal** [comment]
@twangboy Thanks.  I understand the dilemma.  I didn't see any comments or notes anywhere to expect those results so I kind of just wanted to confirm that was the expected behavior.
