### ISSUE TITLE
ERROR: unicode string 

### ISSUE THREAD

**Issue by scheste** [saltstack/salt-winrepo-ng#1566]
I wanted to update and improve the existing state ossec-agent.sls. 
Now I received the following error message and don't know why.

### Error Message:
```
[ERROR   ][2608] A command in 'pkg.refresh_db' had a problem: Error occurred while generating repo db. Additional info follows:

failed:
    1
failed_list:
    ----------
    ossec-agent.sls:
        - Failed to compile, while constructing a mapping
            in "<unicode string>", line 14, column 3:
                '2.9.4':
                ^
          found conflicting ID '3.2.0'
            in "<unicode string>", line 36, column 3:
                '3.2.0':
                ^ 
success:
    1
total:
    2
```

### State:
```
{% set source_path = 'https://updates.atomicorp.com/channels/atomic/windows/' %}

{% if grains['cpuarch'] == 'AMD64' %}
    {% set PROGRAM_FILES = "%ProgramFiles(x86)%" %}
{% else %}
    {% set PROGRAM_FILES = "%ProgramFiles%" %}
{% endif %}

{% set versions = {
'3.2.0':['6132', '6122', '6096'],
'3.1.0':['5732', '5711', '5696'],
'3.0.1':['5667', '5639', '5637', '5636', '5635'],
'3.0.0':['5609', '5607', '5605', '5604', '5602'],
'2.9.4':['5177'],
'2.9.3':['4466', '3861', '3850', '3841', '3840', '2912', '2833', '2817'],
'2.9.2':['2760', '2758', '2154', '2067', '2035', '2021'],
'2.9.0':['2017', '1953', '1801', '1798', '1790', '1780', '1774', '1738'],
} %}

ossec-agent:
{% for major, subversions in versions.items() %}
{% for minor in subversions %}
  '{{ major }}':
    full_name: 'OSSEC HIDS {{ major }}'
    installer: '{{ source_path }}ossec-agent-win32-{{ major }}-{{ minor }}.exe'
    install_flags: '/S'
    uninstaller: '{{ PROGRAM_FILES }}\ossec-agent\uninstall.exe'
    uninstall_flags: '/S'
    msiexec: False
    locale: en_US
    reboot: False
{% endfor %}
{% endfor %}
```

### But...
If I add {{minor}} to the version to the line 25, so that the line looks like:
`  '{{major}}{{minor}}:`
Then I don't get an error message and can at least install the latest version of the agent. But this workaround is wrong, because the minor version specification is only needed for the download and not for install / uninstall.

**Comment by twangboy** [comment]
You probably need to move the line `{% for minor in subversions %}` to be after `  '{{ major }}':`

**Comment by twangboy** [comment]
The `Major` key has to be unique. Each time you loop through it's generating that key again. The problem may be with the way this particular package is storing its version information. It's only reporting the Major version and not the subversions. Salt matches off the version as it appears in "Add/Remove Programs". You may have to just stick with the most recent build of each major version since they're not recording their versions properly in the registry.

**Comment by scheste** [comment]
Thanks a good tip, I have now reduced the versions and only specified the last build version of the respective main version. now it seems to work!
