### ISSUE TITLE
Wireshark: update version and fix full name string

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt-winrepo-ng#1612]

**Comment by artlov** [comment]
Is there any reason to not include Wireshark version 3 to the installer? 3.0.4 is currentrly last available version to download.

**Comment by TerraTalpi** [comment]
Hi @dafyddj  and @artlov, no there is no reason for that, simply no one added the newer versions. I have now added them in the pull request that I have just linked, should be good then. The full name string is also fixed and more importantly the version string. The version string is required for uninstall to match.
