### ISSUE TITLE
install package get minion error log 

### ISSUE THREAD

**Issue by kussatom** [saltstack/salt-winrepo-ng#1627]
in the minion ,the debug info:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\win_reg.py", line 341, in list_keys
    handle = win32api.RegOpenKeyEx(hkey, local_key, 0, access_mask)
pywintypes.error: (2, 'RegOpenKeyEx', 'cann't find file。')
[DEBUG   ] Cannot find key: HKU\S-1-5-19\Software\Microsoft\Installer\Products
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\utils\win_reg.py", line 341, in list_keys
    handle = win32api.RegOpenKeyEx(hkey, local_key, 0, access_mask)
pywintypes.error: (2, 'RegOpenKeyEx', ''cann't find file。')
[DEBUG   ] Cannot find key: HKU\S-1-5-20\Software\Microsoft\Installer\Products
Traceback (most recent call last):

even get the logs ,but  ,the pkg was installed  i don't know why

**Comment by TerraTalpi** [comment]
Can you give us a little bit more info on that? Which package did you install (with which command and what version was installed then)? Which salt-version are you using and which Windows version. Can you still reproduce this?

**Comment by twangboy** [comment]
This is related to this issue in salt: https://github.com/saltstack/salt/issues/53955
Which was fixed with this PR: https://github.com/saltstack/salt/pull/54072
This went into the Salt 3000 release.
