### ISSUE TITLE
salt-winrepo-ng/zabbix-agent.sls

### ISSUE THREAD

**Issue by dpinyol** [saltstack/salt-winrepo-ng#1775]
Hi
salt-winrepo-ng/zabbix-agent.sls url returns 404.

Thanks in advanced.

**Comment by shed909** [comment]
There is a pull request that fixes this here:
https://github.com/saltstack/salt-winrepo-ng/pull/1773

As a temporary solution, we cloned the repo, made the same changes as in the PR above and pointed Salt to our repo.
