### ISSUE TITLE
Should `golang` be (also) available as `go`?

### ISSUE THREAD

**Issue by myii** [saltstack/salt-winrepo-ng#1820]
While adding Windows testing to the [golang-formula](https://github.com/saltstack-formulas/golang-formula/pull/45), our InSpec tests are actually reporting the package installed as `go`, not `golang`.  Does this need to be corrected in any way?

* Referring to https://github.com/saltstack/salt-winrepo-ng/blob/master/golang.sls

**Comment by myii** [comment]
Well, this looks like more of an InSpec issue, since Chocolatey and the Windows Package Manager both using `golang`:

* https://community.chocolatey.org/packages/golang
* https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GoLang

**Comment by TheBigBear** [comment]
@myii can you close the issue then, please?
