### ISSUE TITLE
pkg.refresh_db fails on winrar

### ISSUE THREAD

**Issue by KForney224** [saltstack/salt-winrepo-ng#1913]
When running pkg.refresh_db getting failure to compile winrar:
salt-winrepo-ng\winrar.sls:
        - Failed to compile, Jinja syntax error: expected token ':', got '}'; line 14
          ---
          [...]
              full_name: 'WinRAR {{major}}.{{minor}} (64-bit)'
              installer: '[https://www.rarlab.com/rar/winrar-x64-{{major}}{{minor}}.exe](https://www.rarlab.com/rar/winrar-x64-%7B%7Bmajor%7D%7D%7B%7Bminor%7D%7D.exe)'
              arch: x64
              {% else %}
                full_name: 'WinRAR {{major}}.{{minor}} (32-bit)'
                {% if ({{major}} <= '5') or ({{major}} <= '6' and {{minor}} <= '02') %}    <======================
                  installer: '[https://www.rarlab.com/rar/wrar{{major}}{{minor}}.exe](https://www.rarlab.com/rar/wrar%7B%7Bmajor%7D%7D%7B%7Bminor%7D%7D.exe)'
                {% else %}
                  installer: '[https://www.rarlab.com/rar/winrar-x32-{{major}}{{minor}}.exe](https://www.rarlab.com/rar/winrar-x32-%7B%7Bmajor%7D%7D%7B%7Bminor%7D%7D.exe)'
                {% endif %}
                arch: x86
          [...]
          ---

**Comment by eliasp** [comment]
#1914 was merged - this can be closed.
