### ISSUE TITLE
7z.sls and vlc.sls

### ISSUE THREAD

**Issue by speedytom** [saltstack/salt-winrepo-ng#1956]
<pre>
root@salt:~# salt win-holesovska pkg.refresh_db
win-holesovska:
    ERROR: Error occurred while generating repo db. Additional info follows:
    
    failed:
        2
    failed_list:
        ----------
        salt-winrepo-ng\7zip.sls:
            - Failed to compile, Jinja syntax error: expected token ',', got ':'; line 34
              
              ---
              [...]
              # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              # Below are versions of 7-zip that have had the installer assets removed from the web.
              # An uninstall only definition will remain here so the packages will show up
              # correctly in `pkg.list_pkgs` and to allow for removal using `pkg.remove`
              # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              {% set versions = [ '18':['06', '05', '03', '01'], '16':['04', '03', '02', '00']} %}    <======================
                {% for major, subversions in versions.items() %}
                {% for minor in subversions %}
                  '{{major}}.{{minor}}.00.0':
                    {% if grains['cpuarch'] == 'AMD64' %}
                    full_name: '7-Zip {{major}}.{{minor}} (x64 edition)'
              [...]
              --- 
        salt-winrepo-ng\vlc.sls:
            - Failed to compile, while constructing a mapping
                in "<unicode string>", line 5, column 3
              found conflicting ID '3.0.9.2'
                in "<unicode string>", line 229, column 3 
    success:
        318
    total:
        320
ERROR: Minions returned with non-zero exit code
</pre>

**Comment by speedytom** [comment]
Fixed:
<pre>
diff --git a/7zip.sls b/7zip.sls
index 3c4784d..3ccf3f8 100644
--- a/7zip.sls
+++ b/7zip.sls
@@ -31,7 +31,7 @@
 # An uninstall only definition will remain here so the packages will show up
 # correctly in `pkg.list_pkgs` and to allow for removal using `pkg.remove`
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-{% set versions = [ '18':['06', '05', '03', '01'], '16':['04', '03', '02', '00']} %}
+{% set versions = { '18':['06', '05', '03', '01'], '16':['04', '03', '02', '00']} %}
   {% for major, subversions in versions.items() %}
   {% for minor in subversions %}
     '{{major}}.{{minor}}.00.0':
@@ -52,5 +52,4 @@
       locale: en_US
       reboot: False
   {% endfor %}
-  {% endfor %}
 {% endfor %}
diff --git a/vlc.sls b/vlc.sls
index 2654088..f991cc9 100644
--- a/vlc.sls
+++ b/vlc.sls
@@ -1,7 +1,7 @@
 # both 32-bit (x86) AND a 64-bit (AMD64) installer available
 {% set PROGRAM_FILES = "%ProgramFiles%" %}
 vlc:
-{% for version in ['3.0.17.4', '3.0.17.3', '3.0.17', '3.0.16', '3.0.15', '3.0.14', '3.0.13', '3.0.12,1', '3.0.12', '3.0.11.1', '3.0.11', '3.0.10', '3.0.9.2', '3.0.8', '3.0.7.1', '3.0.7', '3.0.6', '3.0.4'] %}
+{% for version in ['3.0.17.4', '3.0.17.3', '3.0.17', '3.0.16', '3.0.15', '3.0.14', '3.0.13', '3.0.12,1', '3.0.12', '3.0.11.1', '3.0.11', '3.0.10', '3.0.8',   '3.0.6', '3.0.4'] %}
   '{{ version }}':
     full_name: 'VLC media player'
     {% if grains['cpuarch'] == 'AMD64' %}
</pre>

**Comment by speedytom** [comment]
I can push push diff to your master or another branch.

**Comment by TheBigBear** [comment]
@speedytom  this has been fixed soon after the bad versions were merged. But the fixing PR has not yet been merged. see https://github.com/saltstack/salt-winrepo-ng/pull/1949
Thanks. 
@twangboy can you please merge some of these outstanding PRs to avodi others also fixing what has already been fixed?

**Comment by speedytom** [comment]
Thanks for quick response.
