### ISSUE TITLE
unable to update git repos

### ISSUE THREAD

**Issue by mdtabrezpasha** [saltstack/salt-winrepo-ng#2009]
Hello everyone, i am trying to setup Winrepos-ng on my salt master.  doenst seem to be working.  posting the error.  how do i fix this.

![image](https://user-images.githubusercontent.com/50145580/232260224-b06aa488-c39d-4324-aab6-055df1a42e21.png)

**Comment by dafyddj** [comment]
You'll have to provide more information such as the result of `salt --versions`

**Comment by dafyddj** [comment]
Closing due to no response.
