### ISSUE TITLE
Zoom installer on Windows defaults to 32-bit version

### ISSUE THREAD

**Issue by ursacom** [saltstack/salt-winrepo-ng#2053]
zoom.sls
{% set url = "https://www.zoom.us/client/latest/ZoomInstallerFull.msi" %}

This url will install 32-bit latest client, overwriting existing 64 client installed on the system
to make it install 64 bit zoom it should be  
{% set url = "https://www.zoom.us/client/latest/ZoomInstallerFull.msi?archType=x64" %}

The problem is that 32 bit client cannot be upgraded - it can only 
be overwritten with 64 bit installer with higher version

Soon (in march 2024) I believe zoom will drop support to 32 bit versions, so why to default to this?

**Comment by dafyddj** [comment]
I only see that Zoom **Rooms** 32-bit client is EOL March 2024, not the **Meetings** client.
