### ISSUE TITLE
Feature Request: pre/post exec

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt-winrepo-ng#2071]
Some uninstallers are terrible and don't always do The Right Thing.

For example, the Elastic Beats (winlogbeat, auditbeat, etc...) will sometimes fail to stop the service (because winlogbeat.exe is hanged for some reason) and won't uninstall....hanging Salt.  Other installers will install services but not start them.

Currently, my options are (using winlogbeat as an example) to:
* salt 'minion' cmd.run 'taskkill /f /im winlogbeat.exe' which will get the service to eventually stop which will free up the hanged Windows Installer which will cause Salt to stop being hanged waiting on the package removal
* Remember to run the previous command before running a state that installs/uninstalls the package
* Convert the nice "beats.sls" file that installs from the MSI into a kludgy directory with ```cache_dir: true``` and rolling my own powershell and/or batch file that doesn't quite capture return codes properly

I would love to have pre_exec and post_exec options in the definition file that can be run before/after the installer.
Maybe even pre_exec_ignore_failure and post_exec_ignore_failure.

**Comment by dafyddj** [comment]
Please be aware of the latest changes to the Salt Project maintenance policy:
https://docs.saltproject.io/en/master/topics/maintenance-policy.html

**Comment by darkpixel** [comment]
"Feature requests without a PR will be immediately closed."

That's super handy and totally fosters communication in the community...

**Comment by darkpixel** [comment]
"Discussions about features can be held in the GitHub [Discussions](https://github.com/saltstack/salt/discussions) tab"

![Screenshot from 2024-02-20 06-52-55](https://github.com/saltstack/salt-winrepo-ng/assets/158380/c8d5c21f-ee75-41a3-9eed-2acb7886d89b)

**Comment by dafyddj** [comment]
I would suggest the discussion belongs in [saltstack/salt](github.com/saltstack/salt) as that's where the module code resides with a link posted in the Windows channel of the community Slack, if you use that.

**Comment by darkpixel** [comment]
Yes, in the public repo.  We deploy them using the Windows MSI files.
