### ISSUE TITLE
NSClient++ installer URLs broken, like with salt-winrepo

### ISSUE THREAD

**Issue by ArthurMeneau** [saltstack/salt-winrepo-ng#246]
This is almost identical to issue saltstack/salt-winrepo#586 and pull request saltstack/salt-winrepo#587

I will provide a pull request for this shortly.

**Comment by b18** [comment]
Didn't see this issue, but just submitted a pull request for this on the winrepo-ng repo, so disregard if you submit one as well.

**Comment by ameneau-xetus** [comment]
Thanks @b18, 

@TheBigBear looks like this issue was resolved with pull request #247

**Comment by moebiuseye** [comment]
Confirmed. This issue should be closed now.
