### ISSUE TITLE
new 2015.8.4 is on repo , shall I change the salt-winrepo and salt-winrepo-ng sls files?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo-ng#265]
@twangboy @jfindlay I see the new 2015.8.4 is uploaded to the saltstack repo in https://repo.saltstack.com/windows/ is it 'OK' for me to change the salt-winrepo and salt-winrepo-ng salt-minion sls files now?

Or should I wait it out a little longer? 
Until the 2015.8.4 release is official and the ubuntu/debian/rhel etc pkgs are out as well?

**Comment by jfindlay** [comment]
@TheBigBear, the official release announcement should be tomorrow morning, so let's wait until then.

**Comment by TheBigBear** [comment]
@jfindlay OK, I have now gone ahead and update the winrepo and winrepo-ng. this issue can now be closed.
