### ISSUE TITLE
naming of windows salt-minion? (saltstack.minion -> salt-minion) 

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo-ng#301]
@UtahDave @twangboy I see that in the process of updating from the old winrepo to the new winrepo-ng jinja2 templating enabled repo the windows salt-minion's package name got changed from salt-minion to saltstack.minion, BUT the repos sls file name stayed as salt-minion.sls

I would quite like to bring some consistency back and rename the pkg back to salt-minion. The odd name saltstack.minion does not seem to get mentioned on the website or in the docs. 

Was there a deliberate choice to rename the pkg for the windows salt-minion when going from winrepo to winrepo-ng?  

If renaming it is not desired, for fear of upsetting and breaking things in any formulas etc, can I at least then rename the actual sls file itself  to saltstack.minion.sls instead? It would make it the one and only windows ls file that use the '.' (full stop) as a 'name' separator. But at least the names of the sls file itself and the pkg name would be back in 'sync' again?

**Comment by TheBigBear** [comment]
Just looked at the git history, and actually it was me that accidentally renamed it back when it was a WIP branch of the old winrepo. 

https://github.com/TheBigBear/salt-winrepo/commit/71346c15c8fb931191b5e1eef8922231b7f13736#diff-7c7e747afbfb5f190b866de7975bad81

**Comment by UtahDave** [comment]
@TheBigBear did you end up reverting this name change?

**Comment by TheBigBear** [comment]
@UtahDave yep, I did indeed, it is changed to 'salt-minion' as one would expect.
