### ISSUE TITLE
Why are 7zip stable in 7zip beta?

### ISSUE THREAD

**Issue by VietTPham** [saltstack/salt-winrepo-ng#344]
I don't understand why "7zip_beta.sls" has version that are not clearly labeled as beta on there sourceforge page. https://sourceforge.net/projects/sevenzip/files/7-Zip/

**Comment by TheBigBear** [comment]
@VietTPham they used to be beta when added to winrepo,but the website has since re-classified the version numbers. The 'beta' version of the winrepo sls pkg is now gone.  Thanks for raising this.
