### ISSUE TITLE
Using grains['locale_info']['defaultlanguage'] as a locale

### ISSUE THREAD

**Issue by moebiuseye** [saltstack/salt-winrepo-ng#350]
I'm thinking this is probably a good idea for package 
that were translated in a very large number of languages, especialy GUI applications. 

(I have to say I'm very frustrated that the only available 
option is to install things in american english)

For packages that do not provide all translations, 
I may systematicaly try something like this, for every sls file: 

```
# Using defaultlanguage only for available translations
{% if grains['locale_info']['defaultlanguage'] in ['en_US', 'es_ES', 'fr_FR', 'de_DE', 'etc.'] %}
{% set locale = grains['locale_info']['defaultlanguage'] %}
{% else %}
{% set locale = "en_US" %}
{% endif %}
```

And then using that locale variable for the installer: 

```
    - locale: {{locale}}
```

Please tell me if something is preventing us from doing this. 
If we can do this, I'll make a pull request for the following sls files: 
- libreoffice
- openoffice
- firefox
- gimp
- chrome

I will be testing and validating this with Windows Server 2008 RC2 and Windows Seven Pro. 

Please tell me if you know of other software that you think can be safely added to this list. 

Thank you.

**Comment by moebiuseye** [comment]
I've tested this with libreoffice in fr_FR for now, and it's working quite well.

**Comment by twangboy** [comment]
Locale is ignored by winrepo. This feature would need to be added to salt itself.
