### ISSUE TITLE
Visual Studio 2010 Redistributeable install hangs.

### ISSUE THREAD

**Issue by javadevmtl** [saltstack/salt-winrepo-ng#453]
Hi using 2015.8.8.2

I reported the issue here: https://groups.google.com/forum/#!topic/salt-users/Y3aeRDb4Rqs

Using salt on Ubuntu 14.04 to manage some Windows 2008 and 2012 servers.

Everything is setup and running correctly I managed to do some IIS stuff, I even installed firefox as per the docs. But when I run...

sudo salt '*' pkg.install ms-vcpp-2010-sp1-mfc-redist_x64

The command seems to hang. Looking at the minion logs...

```
2016-05-16 16:27:53 [salt.loaded.int.module.cmdmod][INFO    ] Executing command 'Powershell -NonInteractive "Import-Module ServerManager"' in directory 'C:\\Windows\\system32\\config\\systemprofile'
2016-05-16 16:27:53 [salt.minion    ][INFO    ] Starting a new job with PID 2812
2016-05-16 16:27:53 [salt.minion    ][INFO    ] Returning information for job: 20160516162749915989
2016-05-16 16:27:54 [salt.loaded.int.module.cmdmod][INFO    ] Executing command ['c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\download.microsoft.com\\download\\1\\6\\5\\165255E7-1014-4D0A-B094-B6A430A6BFFC\\vcredist_x64.exe', '/qn', '/norestart'] in directory 'c:\\salt\\var\\cache\\salt\\minion\\extrn_files\\base\\download.microsoft.com\\download\\1\\6\\5\\165255E7-1014-4D0A-B094-B6A430A6BFFC'
2016-05-16 16:28:03 [salt.minion    ][INFO    ] Starting a new job with PID 2012
2016-05-16 16:28:03 [salt.minion    ][INFO    ] Returning information for job: 20160516162759925343
2016-05-16 16:28:12 [salt.minion    ][INFO    ] Starting a new job with PID 3024

```

And it goes for ever. I then press ctrl-c get the job id and eventually kill the job manually.

According to this: [How to perform a silent install of the Visual C++ 2010 redistributable packages](https://blogs.msdn.microsoft.com/astebner/2010/10/20/mailbag-how-to-perform-a-silent-install-of-the-visual-c-2010-redistributable-packages/) there is no n flag.

1. Modified the ms-vcpp-2010-sp1-mfc-redist_64.sls file from /qn to /q
2. Updated the minion repo packages.
3. sudo salt '*' pkg.install ms-vcpp-2010-sp1-mfc-redist_x6

The result

```
mywinminion:
    ----------
    _comment:
        Software not found in the registry.
        Could be a problem with the Software
        definition file. Verify the full_name
        and the version match the registry exactly.
        Failed after 10 tries.
    vcredist2010_x64:
        ----------
        new:
            10.0.40219
        old:
```

It seems to be installing but with some error?

**Comment by twangboy** [comment]
@javadevmtl It's not really an error, it's either a timing or a registry refresh issue... it's looking for the software in the registry. If it doesn't find in after 10 tries, it throws this error... I believe this is fixed in 2016.3

**Comment by TheBigBear** [comment]
@twangboy the 'n' flag is a mistake and at least this version of the MS redistributable installer does not support that flag. So I removed that from winrepo and winrepo-ng for both cpuarchs.
When I tested it here, it finished with a error 3010 (successful but machine needs restart. that is possibly the 'error' @javadevmtl is seeing.  (same as reported here https://github.com/saltstack/salt/issues/33298 and  here https://github.com/saltstack/salt-winrepo-ng/issues/141  )

It is definitely a problem that winrepo does not handle exit codes and easily allows windows admins to handle these sort of error codes that are quite common in the windows world.

**Comment by twangboy** [comment]
@TheBigBear Loren Gorden has submitted a PR addressing this issue.
https://github.com/saltstack/salt/pull/33321

**Comment by morganwillcock** [comment]
I think this particular package also has a mistake in the full_name, I've submitted a PR.
#455

**Comment by javadevmtl** [comment]
One more thing to add: 

```
sudo salt 'myminion' pkg.remove ms-vcpp-2010-sp1-mfc-redist_x64
myminion:
    ----------
    ms-vcpp-2010-sp1-mfc-redist_x64:
        ----------
        current:
            not installed

```

It doesn't think it's installed...

**Comment by morganwillcock** [comment]
Have you updated today, to pick up the corrected name?
<pre>Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219</pre>
...there's a double space after 2010 which needs to be there.

You can confirm what is mismatched vs. not installed with `pkg.get_name_map`

**Comment by javadevmtl** [comment]
Oh no I haven't pulled the latest repo... only what I applied to figure this issue.

**Comment by TheBigBear** [comment]
@javadevmtl can you please confirm that we can close this issue now. I believe all the fixes for this pkg are now merged and up to date? thanks for taking the time to report this, muhc appreciated.

**Comment by TheBigBear** [comment]
no feedback to the contrary received. closing this as fixed.
