### ISSUE TITLE
vim installation requires GUI input

### ISSUE THREAD

**Issue by cournape** [saltstack/salt-winrepo-ng#512]
While installing vim from `winrepo-ng` from the minion, I got a dialog asking whether I wanted to install gvim. I suspect that's what caused the salt apply to hang if I do it from the master.

AFAIK, the standard vim installer does not support unattended installation, but the one from the [cream project](https://sourceforge.net/projects/cream/files/Vim/7.4.1641/) does

**Comment by TheBigBear** [comment]
@cournape thanks for this report. update to gvim 8.0.1 and switched to the cream installer for it. fixes issue https://github.com/saltstack/salt-winrepo-ng/issues/512
