### ISSUE TITLE
duplicate ID errors

### ISSUE THREAD

**Issue by danielcb** [saltstack/salt-winrepo-ng#874]
For a view weeks now I keep seeing these errors:

```
failed:
        3
    failed_list:
        ----------
        salt-winrepo-ng\duplicati.sls:
            - package 'duplicati', repo data for version number skip_urltest is not defined as a dictionary
        salt-winrepo-ng\intellij-community.sls:
            - Failed to compile 'salt-winrepo-ng\intellij-community.sls': Conflicting ID '1'
        salt-winrepo-ng\intellij-ultimate.sls:
            - Failed to compile 'salt-winrepo-ng\intellij-ultimate.sls': Conflicting ID '1'
```

Is this related to my setup? As far as I can see both packages use different IDs and a for loop with just one version. I'm not sure where the conflicting ID is coming from.

**Comment by DaveOHenry** [comment]
The sls files are malformed which prevents the minions from updating their package database. Looks like the winrepo is not properly tested / maintained. I think I read somewhere that it is not recommended to directly use the winrepo, because it may break things.
I had the same problem some weeks / months ago ("pkg.install" on Windows minions did not work any more) and ended up just removing the sls files.

I now see the winrepo more as a list of examples. Best approach would be to maintain an own list of software where you can always guarantee that the sls files are correct, the installation files are present and that the software versions match your own requirements.

**Comment by twangboy** [comment]
@danielcb In previous versions of Salt if there was an error in one of the .sls files in the winrepo, the entire refresh_db operation would fail. Now it skips the failures and continues building the repo database. This is just the output when there are .sls files with issues... normal behavior.

**Comment by myii** [comment]
I have a site where the master is version `2016.11.2` and the minions are of various versions including `2016.3.3` and `2016.11.2`.

When using `module.run` for `pkg.refresh_db`, for the `2016.3.3` minions (or older), I get:

```salt
          ID: prepare_winrepo
    Function: module.run
        Name: pkg.refresh_db
      Result: True
     Comment: Module function pkg.refresh_db executed
```

However, when running for the `2016.11.2` minions:

```salt
          ID: prepare_winrepo
    Function: module.run
        Name: pkg.refresh_db
      Result: False
     Comment: Module function pkg.refresh_db threw an exception. Exception: Error occurred while generating repo db. Additional info follows:
              
              failed:
                  3
              failed_list:
                  ----------
                  salt-winrepo-ng\duplicati.sls:
                      - package 'duplicati', repo data for version number skip_urltest is not defined as a dictionary 
                  salt-winrepo-ng\intellij-community.sls:
                      - Failed to compile 'salt-winrepo-ng\intellij-community.sls': Conflicting ID '1'
                  salt-winrepo-ng\intellij-ultimate.sls:
                      - Failed to compile 'salt-winrepo-ng\intellij-ultimate.sls': Conflicting ID '1'
              success:
                  229
              total:
                  232
```

Which is identical to the errors shown at the top of this issue.  @danielcb You've probably started encountering this when you've upgraded your minions.

@DaveOHenry Rather than maintaining one's own lists, there's a lot of mileage to be gained from using `salt.states.chocolatey` and `salt.modules.chocolatey`.  Chocolatey is a very decent alternative.

@twangboy It's good to know that this failure is nothing serious.  My current formula uses a `require` on this `pkg.refresh_db`, so the actual `pkg.installed` doesn't run when it fails.  What's the best way to ignore this failure so that the `pkg.installed` still runs *after* the `pkg.refresh_db`?

**Comment by myii** [comment]
OK, after a cursory look at both `intellij` sls files reveals that both contain:
```salt
{% for version in '14.1.4' %}
```

When this is changed to:

```salt
{% for version in ['14.1.4'] %}
```

These no longer trigger errors when running `pkg.refresh_db`, for the `2016.11.2` minions.

So if the `duplicati` error can be resolved, these changes could be be collected into a PR.

**Comment by myii** [comment]
Looking at `salt-winrepo-ng\duplicati.sls`, a workaround is to simply comment out (or remove) the `skip_urltest` line:

```salt
duplicati:
  # skip_urltest: True
```

Then `pkg.refresh_db` works for all minions, including the `2016.11.2` minions:

```salt
          ID: prepare_winrepo
    Function: module.run
        Name: pkg.refresh_db
      Result: True
     Comment: Module function pkg.refresh_db executed
     ...
     Changes:   
              ----------
              ret:
                  ----------
                  failed:
                      0
                  success:
                      232
                  total:
                      232
```

@TheBigBear I see that this was required for #484 but is there a different way to achieve this?  This is the last resolution required for this issue to be closed.

**Comment by twangboy** [comment]
@myii Try setting `failhard: False` in your state...

**Comment by myii** [comment]
`failhard`... hadn't come across that.  Thanks for that.

**Comment by myii** [comment]
@twangboy OK, just had an opportunity to test `failhard: False` and it still results in the state failing, so that the subsequent `require` prevents the `pkg.installed` state from running.

```salt
prepare_winrepo:
  module.run:
    - name: pkg.refresh_db
    - failhard: False
```

Results in:

```salt
          ID: prepare_winrepo
    Function: module.run
        Name: pkg.refresh_db
      Result: False
     Comment: Module function pkg.refresh_db threw an exception. Exception: Error occurred while generating repo db. Additional info follows:
              
              failed:
                  1
              failed_list:
                  ----------
                  salt-winrepo-ng\duplicati.sls:
                      - package 'duplicati', repo data for version number skip_urltest is not defined as a dictionary 
              success:
                  231
              total:
                  232
     ...
     Changes:   
----------
          ID: install_tightvnc
    Function: pkg.installed
        Name: tightvnc
      Result: False
     Comment: One or more requisite failed: bootstrap_windows.winrepo.prepare_winrepo
     Changes:
```

So this is essentially the same outcome as running without `failhard: False`.

**Comment by twangboy** [comment]
@myii You could try `pkg.installed` with `refresh: True`

**Comment by twangboy** [comment]
@myii In fact, it looks like refreshing the database is default behavior for `pkg.installed`

**Comment by myii** [comment]
@twangboy I was just about to say that as you commented!  I was just running tests on one of the minions and I found exactly that.

1. On the minion, deleted all of the cached `sls` files in `C:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng`
1. Ran the formula without the `pkg.refresh_db` state
1. Used `pkg.installed` without `refresh: True`
1. Saw that the refresh took place anyway

Not important but this now leads to the question: when is `pkg.refresh_db` actually required?

**Comment by damon-atkins** [comment]
I change a lot of pkg.refresh_db code which was introduced into 2016.11
- It now reports errors.   People would do a pkg.install and not know why it would not work
- A new internal function refresh the meta data automatically. Their are new options to control this winrepo_cache_*   The default is 6 hours old then refresh.  I made it behaviour more like Unix/Linux package managers

Basically you should not need to call pkg.refresh_db unless you are writing a new package definition and want to see if it has any errors, or you just updated a current definition and want to test it in less than 6 hours time.

**Comment by damon-atkins** [comment]
The issue you are having is that the sls file is not structure correctly and will never work.   So when 2016.11 was first change. I put Issues into fix any sls files in the git hub repo.  So more must of appear with bad data.  I suggest you raise a Issue against  https://github.com/saltstack/salt-winrepo-ng

**Comment by damon-atkins** [comment]
If you have windows, then you need to be on the latest 2016.11 their are heaps of package management fixes.  For example refresh_db was being over called in some circumstances slowing everything down.

I also introduced into cmd.shell_info which allowed powershell version to be detected without running powershell.  i.e. powershell is very slow to start. And Salt needs to run powershell to check its version now and them.

I strongly suggest you upgrade to latest 2016.11 on windows on all windows servers/desktops

**Comment by damon-atkins** [comment]
Only one sls file can contain a definition for something. Having more than one results in not know which is being used.

**Comment by damon-atkins** [comment]
Have you updated your copy of salt-winrepo-ng?

**Comment by myii** [comment]
@damon-atkins Thanks for all of the feedback.

1. I'm considering submitting a PR but I was just waiting for a response about `salt-winrepo-ng\duplicati.sls` (problem with `skip_urltest`), so that all 3 errors could be resolved
1. Upgrading all minions to `2016.11` is ideal but not easy to achieve at the current time -- I will have to support older minions for the time being, so I'll have to modify my formulas accordingly
1. Otherwise, the information in this thread has been very useful and I believe I have enough to work with in my situation

**Comment by damon-atkins** [comment]
skip_urltest not valid in a sls file. I have not seen any code to use this value.  What its saying is it expects a hash/dict next not a key/value pair   i.e. Normal it would be a dict of 'version' which goes on to contain key/value pairs.  

I had code to check the structure of the files, to catch mistakes like this. However it does not check everything.  e.g. if skip_urltest was under the version it would have ignored it.

**Comment by myii** [comment]
Following through from #484 shows that `skip_urltest` is/was used by Travis-CI.  The original commit by @TheBigBear was `Add non standard duplicati.sls travis-ci_skip-flag`.  So was always _non-standard_.

Ideally, we need to find out if this can be put under the version or removed entirely or find some other solution for this.

**Comment by TheBigBear** [comment]
@myii Sorry about the duplicati 'travis-ci_skip-flag'. 

FYI, I am NOT a coder, I help out in this project by merging in PRs. 

The change was introduced by @moebiuseye, back when he introduced this there were no immediate error messages highlighting the fact that this was 'non-standard'.

@moebiuseye had planned (and promised) to come back after his exams to clean-up this and code up an alternative solution, to the original problem. 

But if looks very much life got the better of him, it has been a few months now without any feedback or further updates or fixes.

Yes, the 'skip-urltest' is still in active use over on the travis-ci servers, but I guess it might be fair to 'remove' the non-standard 'skip-urltest' flag from that single sls file. 

And hope somebody will step up to the challenge some day and come up with a better and modular solution that doesn't cause error messages.

**Comment by moebiuseye** [comment]
Hi, everyone; I'm looking at the problem and might make a PR later today. For now, I agree : you should remove the non-standard `skip-urltest` flag.

**Comment by damon-atkins** [comment]
These sls files are not really sls files. But more of a package definition file.

**Comment by myii** [comment]
@TheBigBear Thanks for getting back.  Removing `skip-urltest` means that all 3 errors can now be resolved.

@moebiuseye I was just working on the PR, so don't worry -- was waiting for this final confirmation.

**Comment by myii** [comment]
With the PR merged, I believe this issue can be closed -- can you do that @danielcb?

Thanks to everyone for their help and feedback.

**Comment by danielcb** [comment]
Thanks!
