### ISSUE TITLE
Missing ' in virtualbox.sls

### ISSUE THREAD

**Issue by abaldoni** [saltstack/salt-winrepo-ng#944]
virtualbox.sls is missing a closing ' in the following line

full_name: 'Oracle VM VirtualBox 5.1.16

**Comment by TheBigBear** [comment]
@mercsniper https://github.com/saltstack/salt-winrepo-ng/commit/7ba44b75dbe182cb2c6f72fd192202cecd6c0fe0 will you do a PR?

**Comment by abaldoni** [comment]
Sure, I'll let you know by tomorrow.Il 19 apr 2017 17:49, TheBigBear <notifications@github.com> ha scritto:@mercsniper 7ba44b7 will you do a PR?

**Comment by danielcb** [comment]
already done and merged: #943

**Comment by abaldoni** [comment]
Thanks!
